### ISSUE TITLE
Npm package needs update

### ISSUE THREAD

**Issue by brfalcon** [dequelabs/grunt-axe-webdriver#20]
Hello, @dylanb! How are you doing?

I've noticed that the npm package is missing the changes since your commit [a6f8983](https://github.com/dequelabs/grunt-axe-webdriver/commit/a6f89831ee200b9291c306022b32d828eba3b563) on Aug 2, 2016.

Would it be possible to update the npm package?

Regards,
Vinicius

**Comment by marcysutton** [comment]
That's on my plate, I'll pick it up as soon as I get a chance. Sorry for the delay!

**Comment by brfalcon** [comment]
Awesome! Thanks @marcysutton 
I am working with a local version but I am looking forward to use it straight from npm.

**Comment by marcysutton** [comment]
It is now published. https://www.npmjs.com/package/grunt-axe-webdriver
