### ISSUE TITLE
installing version 0.0.3 with npm@5 fails

### ISSUE THREAD

**Issue by chrisguttandin** [dequelabs/grunt-axe-webdriver#23]
Hi, I just discovered that version 0.0.3 seems to be not installable with npm version 5. I'm not 100% sure but I think it's because axe-webdriverjs needs to be installed from GitHub and the path inside the package.json does not contain a hash.

Anyway, I've seen that that was already changed on master and axe-webdriverjs is now required from npm again. Can you maybe release another version with the update package.json?

**Comment by marcysutton** [comment]
0.0.4 has been published and it worked for me!

**Comment by chrisguttandin** [comment]
thank you very much
