### ISSUE TITLE
Getting Firefox working (Chrome works out of the box)

### ISSUE THREAD

**Issue by jnachtigall** [dequelabs/grunt-axe-webdriver#27]
I'm new to axe and selenium. From what I noticed Chrome works out of the box because grunt-axe-webdriver depends the npm [chromedriver](https://www.npmjs.com/package/chromedriver) package which is installed into `node_modules/.bin/`. Firefox does not work out of the box, although there is [geckodriver](https://www.npmjs.com/package/geckodriver). 

I manually added geckodriver to my project:
```
$ npm install geckodriver --save-dev
```

But it looks like this is not enough to get Firefox working out of the box, I'm still getting:

```
$ node_modules/.bin/grunt axe-webdriver
Running "axe-webdriver:firefox" (axe-webdriver) task
Fatal error: Timed out waiting for the WebDriver server at http://127.0.0.1:63179/hub
```

Firefox launches but the given URLs are not loaded. The Chrome config works. I am on Windows 10.

My config is as follows:
```
{
    firefox: {
      options: {},
      urls: [
        'http://www.ard.de/home/ard/ARD_Startseite/21920/index.html',
        'http://www.zeit.de/index'
      ],
      dest: 'output.json',
      junitDest: 'output.xml'
    },
    chrome: {
      options: {
        browser: 'chrome'
      },
      urls: [
        'http://www.ard.de/home/ard/ARD_Startseite/21920/index.html',
        'http://www.zeit.de/index'
      ],
      dest: 'output.json',
      junitDest: 'output.xml'
    }
  }
```

PS If you have a pointer/link on how to get this working with Firefox or Chrome in headless mode, I would really very much appreciate <3

**Comment by WilcoFiers** [comment]
Just going by the config, I'm guessing you need to add `browser: 'firefox'` to your options object.

**Comment by jnachtigall** [comment]
@WilcoFiers No, that's not changing anything: Firefox launches, just the `urls` are not loaded. Also [the docs under Additional Browser](https://github.com/dequelabs/grunt-axe-webdriver#additional-browser) say `browser: 'firefox'` is default and not necessary.
