### ISSUE TITLE
Please release a new npm version

### ISSUE THREAD

**Issue by jnachtigall** [dequelabs/grunt-axe-webdriver#32]
Now that my PRs have been merged (thanks ❤️ ) it would be awesome if a new npm version could be put to https://www.npmjs.com/package/grunt-axe-webdriver so that I can refer to the official URL in our project's `package.json`. At the moment I still have `    "grunt-axe-webdriver": "github:jnachtigall/grunt-axe-webdriver#Add_geckodriver"` in it but would love to replace this.

FWIW, I noticed that there's also no releases at https://github.com/dequelabs/grunt-axe-webdriver/releases whereas there are 5 different ones at npmjs.com. I'd recommend release-it to do the releases nice and quickly withing just a few seconds: https://www.npmjs.com/package/release-it

**Comment by WilcoFiers** [comment]
One of the tests was failing since the last PR. I just created a fix for it. We should be able to publish now.

**Comment by WilcoFiers** [comment]
Should be available now.
