### ISSUE TITLE
How to increase the webdriver timeout?

### ISSUE THREAD

**Issue by jnachtigall** [dequelabs/grunt-axe-webdriver#35]
Our grunt task now checks a lot of pages and this causes an error:
```
Running "axe-webdriver:firefox" (axe-webdriver) task
Fatal error: Timed out after 30000 ms
error Command failed with exit code 3.
```

If I reduce the number of pages to be checked, then it works fine. So it's really the problem that it takes too long.

How can I increase the timeout? I don't see an option or anything for this. Also, I am not sure where in the dependencies one would best set this: selenium or webdriver or anywhere else?

**Comment by marcysutton** [comment]
@jnachtigall here's how it works in axe-webdriverjs by itself:

```javascript
const selenium = require('selenium-webdriver')

driver = new selenium.Builder()
            .forBrowser('chrome');

        browser = driver.build();

        browser.manage().timeouts().setScriptTimeout(60000);
```
These details are abstracted away by this plugin. We would probably need to add an option to override the default timeout, which internally would resemble the above code.
