### ISSUE TITLE
Naming scheme not in line with convention for grunt plugins

### ISSUE THREAD

**Issue by arschmitz** [dequelabs/grunt-axe-webdriver#6]
Grunt plugins follow the naming scheme `grunt-name` and tools built for loading grunt plugins expect this pattern. This means that by default this plugin will not be loaded when using things like `grunt-load-config` and `load-grunt-tasks` since this repo is still so new ( only a few days ). It seems like it might be good to update the name.

**Comment by dsturley** [comment]
I agree.

We should change to `grunt-axe-webdriver` npm module name and `axe-webdriver` task name.
